name: CI/CD Pipeline Web Homepage

env:
  PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
  HOST_NAME: ${{secrets.SSH_HOST_NAME}}
  USER_NAME: ${{secrets.SSH_USER}}

on:
  push:
    branches: [main]

jobs:
  # Build Image
  build-and-push-image:
    strategy:
      matrix:
        node-version: [20]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        run: sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        run: |
          sudo docker build -t greenapps/homepage:latest -f Dockerfile .
          sudo docker push greenapps/homepage:latest
          echo "Compile complete."

  # Deploy to server
  deploy-to-server:
    needs: [ build-and-push-image ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Deploy to EC2
        run: |
          echo "Starting deploy"
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST_NAME} '
            cd gm4-homepage &&
            git pull origin main &&
            docker pull greenapps/homepage:latest &&
            docker-compose down &&
            docker-compose up -d &&
            docker image prune -f
          '
          echo "Deploy Successful"